run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
  skip-dirs:
  skip-files:
  modules-download-mode: readonly

output:
  format: tab
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - dupword # Checks for duplicate words in the source code.
    - gci # Gci controls Go package import order and makes it always deterministic.
    - gocognit # Computes and checks the cognitive complexity of functions.
    - gocritic # Provides diagnostics that check for bugs, performance and style issues.
    - godox # Tool for detection of FIXME, TODO and other comment keywords.
    - govet # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string.
    - misspell # Finds commonly misspelled English words in comments.
    - nestif # Reports deeply nested if statements.
    - nlreturn # Nlreturn checks for a new line before return and branch statements to increase code clarity.
    - staticcheck # It's a set of rules from staticcheck.
    - typecheck
  enable-all: false
  disable:
  disable-all: true
  presets:
  fast: false

linters-settings:
  gocognit:
    min-complexity: 20

  gocritic:
    enabled-checks:
    disabled-checks:
      - paramTypeCombine
      - importShadow
    enabled-tags:
      - diagnostic
      - style
      - experimental
      - opinionated
    disabled-tags:
    settings:

  godox:
    keywords:
      - TODO
      - BUG
      - FIXME

  nestif:
    min-complexity: 4

issues:
  exclude-rules:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
